// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node.proto

package org.serdaroquai.pml;

public final class NodeProto {
  private NodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.serdaroquai.pml.Node)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
     */
    boolean hasE();
    /**
     * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
     */
    org.serdaroquai.pml.NodeProto.ExtensionNode getE();
    /**
     * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
     */
    org.serdaroquai.pml.NodeProto.ExtensionNodeOrBuilder getEOrBuilder();

    /**
     * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
     */
    boolean hasV();
    /**
     * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
     */
    org.serdaroquai.pml.NodeProto.ValueNode getV();
    /**
     * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
     */
    org.serdaroquai.pml.NodeProto.ValueNodeOrBuilder getVOrBuilder();

    public org.serdaroquai.pml.NodeProto.Node.NodeCase getNodeCase();
  }
  /**
   * Protobuf type {@code org.serdaroquai.pml.Node}
   */
  public  static final class Node extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.serdaroquai.pml.Node)
      NodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Node.newBuilder() to construct.
    private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Node() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Node(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.serdaroquai.pml.NodeProto.ExtensionNode.Builder subBuilder = null;
              if (nodeCase_ == 1) {
                subBuilder = ((org.serdaroquai.pml.NodeProto.ExtensionNode) node_).toBuilder();
              }
              node_ =
                  input.readMessage(org.serdaroquai.pml.NodeProto.ExtensionNode.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((org.serdaroquai.pml.NodeProto.ExtensionNode) node_);
                node_ = subBuilder.buildPartial();
              }
              nodeCase_ = 1;
              break;
            }
            case 18: {
              org.serdaroquai.pml.NodeProto.ValueNode.Builder subBuilder = null;
              if (nodeCase_ == 2) {
                subBuilder = ((org.serdaroquai.pml.NodeProto.ValueNode) node_).toBuilder();
              }
              node_ =
                  input.readMessage(org.serdaroquai.pml.NodeProto.ValueNode.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((org.serdaroquai.pml.NodeProto.ValueNode) node_);
                node_ = subBuilder.buildPartial();
              }
              nodeCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_Node_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_Node_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.serdaroquai.pml.NodeProto.Node.class, org.serdaroquai.pml.NodeProto.Node.Builder.class);
    }

    private int nodeCase_ = 0;
    private java.lang.Object node_;
    public enum NodeCase
        implements com.google.protobuf.Internal.EnumLite {
      E(1),
      V(2),
      NODE_NOT_SET(0);
      private final int value;
      private NodeCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NodeCase valueOf(int value) {
        return forNumber(value);
      }

      public static NodeCase forNumber(int value) {
        switch (value) {
          case 1: return E;
          case 2: return V;
          case 0: return NODE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public NodeCase
    getNodeCase() {
      return NodeCase.forNumber(
          nodeCase_);
    }

    public static final int E_FIELD_NUMBER = 1;
    /**
     * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
     */
    public boolean hasE() {
      return nodeCase_ == 1;
    }
    /**
     * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
     */
    public org.serdaroquai.pml.NodeProto.ExtensionNode getE() {
      if (nodeCase_ == 1) {
         return (org.serdaroquai.pml.NodeProto.ExtensionNode) node_;
      }
      return org.serdaroquai.pml.NodeProto.ExtensionNode.getDefaultInstance();
    }
    /**
     * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
     */
    public org.serdaroquai.pml.NodeProto.ExtensionNodeOrBuilder getEOrBuilder() {
      if (nodeCase_ == 1) {
         return (org.serdaroquai.pml.NodeProto.ExtensionNode) node_;
      }
      return org.serdaroquai.pml.NodeProto.ExtensionNode.getDefaultInstance();
    }

    public static final int V_FIELD_NUMBER = 2;
    /**
     * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
     */
    public boolean hasV() {
      return nodeCase_ == 2;
    }
    /**
     * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
     */
    public org.serdaroquai.pml.NodeProto.ValueNode getV() {
      if (nodeCase_ == 2) {
         return (org.serdaroquai.pml.NodeProto.ValueNode) node_;
      }
      return org.serdaroquai.pml.NodeProto.ValueNode.getDefaultInstance();
    }
    /**
     * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
     */
    public org.serdaroquai.pml.NodeProto.ValueNodeOrBuilder getVOrBuilder() {
      if (nodeCase_ == 2) {
         return (org.serdaroquai.pml.NodeProto.ValueNode) node_;
      }
      return org.serdaroquai.pml.NodeProto.ValueNode.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nodeCase_ == 1) {
        output.writeMessage(1, (org.serdaroquai.pml.NodeProto.ExtensionNode) node_);
      }
      if (nodeCase_ == 2) {
        output.writeMessage(2, (org.serdaroquai.pml.NodeProto.ValueNode) node_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nodeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (org.serdaroquai.pml.NodeProto.ExtensionNode) node_);
      }
      if (nodeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (org.serdaroquai.pml.NodeProto.ValueNode) node_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.serdaroquai.pml.NodeProto.Node)) {
        return super.equals(obj);
      }
      org.serdaroquai.pml.NodeProto.Node other = (org.serdaroquai.pml.NodeProto.Node) obj;

      if (!getNodeCase().equals(other.getNodeCase())) return false;
      switch (nodeCase_) {
        case 1:
          if (!getE()
              .equals(other.getE())) return false;
          break;
        case 2:
          if (!getV()
              .equals(other.getV())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (nodeCase_) {
        case 1:
          hash = (37 * hash) + E_FIELD_NUMBER;
          hash = (53 * hash) + getE().hashCode();
          break;
        case 2:
          hash = (37 * hash) + V_FIELD_NUMBER;
          hash = (53 * hash) + getV().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.serdaroquai.pml.NodeProto.Node parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.serdaroquai.pml.NodeProto.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.serdaroquai.pml.NodeProto.Node prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.serdaroquai.pml.Node}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.serdaroquai.pml.Node)
        org.serdaroquai.pml.NodeProto.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_Node_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.serdaroquai.pml.NodeProto.Node.class, org.serdaroquai.pml.NodeProto.Node.Builder.class);
      }

      // Construct using org.serdaroquai.pml.NodeProto.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nodeCase_ = 0;
        node_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_Node_descriptor;
      }

      @java.lang.Override
      public org.serdaroquai.pml.NodeProto.Node getDefaultInstanceForType() {
        return org.serdaroquai.pml.NodeProto.Node.getDefaultInstance();
      }

      @java.lang.Override
      public org.serdaroquai.pml.NodeProto.Node build() {
        org.serdaroquai.pml.NodeProto.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.serdaroquai.pml.NodeProto.Node buildPartial() {
        org.serdaroquai.pml.NodeProto.Node result = new org.serdaroquai.pml.NodeProto.Node(this);
        if (nodeCase_ == 1) {
          if (eBuilder_ == null) {
            result.node_ = node_;
          } else {
            result.node_ = eBuilder_.build();
          }
        }
        if (nodeCase_ == 2) {
          if (vBuilder_ == null) {
            result.node_ = node_;
          } else {
            result.node_ = vBuilder_.build();
          }
        }
        result.nodeCase_ = nodeCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.serdaroquai.pml.NodeProto.Node) {
          return mergeFrom((org.serdaroquai.pml.NodeProto.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.serdaroquai.pml.NodeProto.Node other) {
        if (other == org.serdaroquai.pml.NodeProto.Node.getDefaultInstance()) return this;
        switch (other.getNodeCase()) {
          case E: {
            mergeE(other.getE());
            break;
          }
          case V: {
            mergeV(other.getV());
            break;
          }
          case NODE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.serdaroquai.pml.NodeProto.Node parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.serdaroquai.pml.NodeProto.Node) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int nodeCase_ = 0;
      private java.lang.Object node_;
      public NodeCase
          getNodeCase() {
        return NodeCase.forNumber(
            nodeCase_);
      }

      public Builder clearNode() {
        nodeCase_ = 0;
        node_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          org.serdaroquai.pml.NodeProto.ExtensionNode, org.serdaroquai.pml.NodeProto.ExtensionNode.Builder, org.serdaroquai.pml.NodeProto.ExtensionNodeOrBuilder> eBuilder_;
      /**
       * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
       */
      public boolean hasE() {
        return nodeCase_ == 1;
      }
      /**
       * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
       */
      public org.serdaroquai.pml.NodeProto.ExtensionNode getE() {
        if (eBuilder_ == null) {
          if (nodeCase_ == 1) {
            return (org.serdaroquai.pml.NodeProto.ExtensionNode) node_;
          }
          return org.serdaroquai.pml.NodeProto.ExtensionNode.getDefaultInstance();
        } else {
          if (nodeCase_ == 1) {
            return eBuilder_.getMessage();
          }
          return org.serdaroquai.pml.NodeProto.ExtensionNode.getDefaultInstance();
        }
      }
      /**
       * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
       */
      public Builder setE(org.serdaroquai.pml.NodeProto.ExtensionNode value) {
        if (eBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          node_ = value;
          onChanged();
        } else {
          eBuilder_.setMessage(value);
        }
        nodeCase_ = 1;
        return this;
      }
      /**
       * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
       */
      public Builder setE(
          org.serdaroquai.pml.NodeProto.ExtensionNode.Builder builderForValue) {
        if (eBuilder_ == null) {
          node_ = builderForValue.build();
          onChanged();
        } else {
          eBuilder_.setMessage(builderForValue.build());
        }
        nodeCase_ = 1;
        return this;
      }
      /**
       * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
       */
      public Builder mergeE(org.serdaroquai.pml.NodeProto.ExtensionNode value) {
        if (eBuilder_ == null) {
          if (nodeCase_ == 1 &&
              node_ != org.serdaroquai.pml.NodeProto.ExtensionNode.getDefaultInstance()) {
            node_ = org.serdaroquai.pml.NodeProto.ExtensionNode.newBuilder((org.serdaroquai.pml.NodeProto.ExtensionNode) node_)
                .mergeFrom(value).buildPartial();
          } else {
            node_ = value;
          }
          onChanged();
        } else {
          if (nodeCase_ == 1) {
            eBuilder_.mergeFrom(value);
          }
          eBuilder_.setMessage(value);
        }
        nodeCase_ = 1;
        return this;
      }
      /**
       * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
       */
      public Builder clearE() {
        if (eBuilder_ == null) {
          if (nodeCase_ == 1) {
            nodeCase_ = 0;
            node_ = null;
            onChanged();
          }
        } else {
          if (nodeCase_ == 1) {
            nodeCase_ = 0;
            node_ = null;
          }
          eBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
       */
      public org.serdaroquai.pml.NodeProto.ExtensionNode.Builder getEBuilder() {
        return getEFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
       */
      public org.serdaroquai.pml.NodeProto.ExtensionNodeOrBuilder getEOrBuilder() {
        if ((nodeCase_ == 1) && (eBuilder_ != null)) {
          return eBuilder_.getMessageOrBuilder();
        } else {
          if (nodeCase_ == 1) {
            return (org.serdaroquai.pml.NodeProto.ExtensionNode) node_;
          }
          return org.serdaroquai.pml.NodeProto.ExtensionNode.getDefaultInstance();
        }
      }
      /**
       * <code>.org.serdaroquai.pml.ExtensionNode e = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.serdaroquai.pml.NodeProto.ExtensionNode, org.serdaroquai.pml.NodeProto.ExtensionNode.Builder, org.serdaroquai.pml.NodeProto.ExtensionNodeOrBuilder> 
          getEFieldBuilder() {
        if (eBuilder_ == null) {
          if (!(nodeCase_ == 1)) {
            node_ = org.serdaroquai.pml.NodeProto.ExtensionNode.getDefaultInstance();
          }
          eBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.serdaroquai.pml.NodeProto.ExtensionNode, org.serdaroquai.pml.NodeProto.ExtensionNode.Builder, org.serdaroquai.pml.NodeProto.ExtensionNodeOrBuilder>(
                  (org.serdaroquai.pml.NodeProto.ExtensionNode) node_,
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        nodeCase_ = 1;
        onChanged();;
        return eBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          org.serdaroquai.pml.NodeProto.ValueNode, org.serdaroquai.pml.NodeProto.ValueNode.Builder, org.serdaroquai.pml.NodeProto.ValueNodeOrBuilder> vBuilder_;
      /**
       * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
       */
      public boolean hasV() {
        return nodeCase_ == 2;
      }
      /**
       * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
       */
      public org.serdaroquai.pml.NodeProto.ValueNode getV() {
        if (vBuilder_ == null) {
          if (nodeCase_ == 2) {
            return (org.serdaroquai.pml.NodeProto.ValueNode) node_;
          }
          return org.serdaroquai.pml.NodeProto.ValueNode.getDefaultInstance();
        } else {
          if (nodeCase_ == 2) {
            return vBuilder_.getMessage();
          }
          return org.serdaroquai.pml.NodeProto.ValueNode.getDefaultInstance();
        }
      }
      /**
       * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
       */
      public Builder setV(org.serdaroquai.pml.NodeProto.ValueNode value) {
        if (vBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          node_ = value;
          onChanged();
        } else {
          vBuilder_.setMessage(value);
        }
        nodeCase_ = 2;
        return this;
      }
      /**
       * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
       */
      public Builder setV(
          org.serdaroquai.pml.NodeProto.ValueNode.Builder builderForValue) {
        if (vBuilder_ == null) {
          node_ = builderForValue.build();
          onChanged();
        } else {
          vBuilder_.setMessage(builderForValue.build());
        }
        nodeCase_ = 2;
        return this;
      }
      /**
       * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
       */
      public Builder mergeV(org.serdaroquai.pml.NodeProto.ValueNode value) {
        if (vBuilder_ == null) {
          if (nodeCase_ == 2 &&
              node_ != org.serdaroquai.pml.NodeProto.ValueNode.getDefaultInstance()) {
            node_ = org.serdaroquai.pml.NodeProto.ValueNode.newBuilder((org.serdaroquai.pml.NodeProto.ValueNode) node_)
                .mergeFrom(value).buildPartial();
          } else {
            node_ = value;
          }
          onChanged();
        } else {
          if (nodeCase_ == 2) {
            vBuilder_.mergeFrom(value);
          }
          vBuilder_.setMessage(value);
        }
        nodeCase_ = 2;
        return this;
      }
      /**
       * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
       */
      public Builder clearV() {
        if (vBuilder_ == null) {
          if (nodeCase_ == 2) {
            nodeCase_ = 0;
            node_ = null;
            onChanged();
          }
        } else {
          if (nodeCase_ == 2) {
            nodeCase_ = 0;
            node_ = null;
          }
          vBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
       */
      public org.serdaroquai.pml.NodeProto.ValueNode.Builder getVBuilder() {
        return getVFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
       */
      public org.serdaroquai.pml.NodeProto.ValueNodeOrBuilder getVOrBuilder() {
        if ((nodeCase_ == 2) && (vBuilder_ != null)) {
          return vBuilder_.getMessageOrBuilder();
        } else {
          if (nodeCase_ == 2) {
            return (org.serdaroquai.pml.NodeProto.ValueNode) node_;
          }
          return org.serdaroquai.pml.NodeProto.ValueNode.getDefaultInstance();
        }
      }
      /**
       * <code>.org.serdaroquai.pml.ValueNode v = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.serdaroquai.pml.NodeProto.ValueNode, org.serdaroquai.pml.NodeProto.ValueNode.Builder, org.serdaroquai.pml.NodeProto.ValueNodeOrBuilder> 
          getVFieldBuilder() {
        if (vBuilder_ == null) {
          if (!(nodeCase_ == 2)) {
            node_ = org.serdaroquai.pml.NodeProto.ValueNode.getDefaultInstance();
          }
          vBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.serdaroquai.pml.NodeProto.ValueNode, org.serdaroquai.pml.NodeProto.ValueNode.Builder, org.serdaroquai.pml.NodeProto.ValueNodeOrBuilder>(
                  (org.serdaroquai.pml.NodeProto.ValueNode) node_,
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        nodeCase_ = 2;
        onChanged();;
        return vBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.serdaroquai.pml.Node)
    }

    // @@protoc_insertion_point(class_scope:org.serdaroquai.pml.Node)
    private static final org.serdaroquai.pml.NodeProto.Node DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.serdaroquai.pml.NodeProto.Node();
    }

    public static org.serdaroquai.pml.NodeProto.Node getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Node>
        PARSER = new com.google.protobuf.AbstractParser<Node>() {
      @java.lang.Override
      public Node parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Node(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Node> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Node> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.serdaroquai.pml.NodeProto.Node getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExtensionNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.serdaroquai.pml.ExtensionNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>bytes value = 2;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code org.serdaroquai.pml.ExtensionNode}
   */
  public  static final class ExtensionNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.serdaroquai.pml.ExtensionNode)
      ExtensionNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExtensionNode.newBuilder() to construct.
    private ExtensionNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExtensionNode() {
      key_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExtensionNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {

              value_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ExtensionNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ExtensionNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.serdaroquai.pml.NodeProto.ExtensionNode.class, org.serdaroquai.pml.NodeProto.ExtensionNode.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.serdaroquai.pml.NodeProto.ExtensionNode)) {
        return super.equals(obj);
      }
      org.serdaroquai.pml.NodeProto.ExtensionNode other = (org.serdaroquai.pml.NodeProto.ExtensionNode) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.serdaroquai.pml.NodeProto.ExtensionNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.serdaroquai.pml.NodeProto.ExtensionNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.serdaroquai.pml.ExtensionNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.serdaroquai.pml.ExtensionNode)
        org.serdaroquai.pml.NodeProto.ExtensionNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ExtensionNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ExtensionNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.serdaroquai.pml.NodeProto.ExtensionNode.class, org.serdaroquai.pml.NodeProto.ExtensionNode.Builder.class);
      }

      // Construct using org.serdaroquai.pml.NodeProto.ExtensionNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        value_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ExtensionNode_descriptor;
      }

      @java.lang.Override
      public org.serdaroquai.pml.NodeProto.ExtensionNode getDefaultInstanceForType() {
        return org.serdaroquai.pml.NodeProto.ExtensionNode.getDefaultInstance();
      }

      @java.lang.Override
      public org.serdaroquai.pml.NodeProto.ExtensionNode build() {
        org.serdaroquai.pml.NodeProto.ExtensionNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.serdaroquai.pml.NodeProto.ExtensionNode buildPartial() {
        org.serdaroquai.pml.NodeProto.ExtensionNode result = new org.serdaroquai.pml.NodeProto.ExtensionNode(this);
        result.key_ = key_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.serdaroquai.pml.NodeProto.ExtensionNode) {
          return mergeFrom((org.serdaroquai.pml.NodeProto.ExtensionNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.serdaroquai.pml.NodeProto.ExtensionNode other) {
        if (other == org.serdaroquai.pml.NodeProto.ExtensionNode.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.serdaroquai.pml.NodeProto.ExtensionNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.serdaroquai.pml.NodeProto.ExtensionNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.serdaroquai.pml.ExtensionNode)
    }

    // @@protoc_insertion_point(class_scope:org.serdaroquai.pml.ExtensionNode)
    private static final org.serdaroquai.pml.NodeProto.ExtensionNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.serdaroquai.pml.NodeProto.ExtensionNode();
    }

    public static org.serdaroquai.pml.NodeProto.ExtensionNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExtensionNode>
        PARSER = new com.google.protobuf.AbstractParser<ExtensionNode>() {
      @java.lang.Override
      public ExtensionNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExtensionNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExtensionNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExtensionNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.serdaroquai.pml.NodeProto.ExtensionNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValueNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.serdaroquai.pml.ValueNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes value = 1;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code org.serdaroquai.pml.ValueNode}
   */
  public  static final class ValueNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.serdaroquai.pml.ValueNode)
      ValueNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValueNode.newBuilder() to construct.
    private ValueNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValueNode() {
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValueNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              value_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ValueNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ValueNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.serdaroquai.pml.NodeProto.ValueNode.class, org.serdaroquai.pml.NodeProto.ValueNode.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 1;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!value_.isEmpty()) {
        output.writeBytes(1, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.serdaroquai.pml.NodeProto.ValueNode)) {
        return super.equals(obj);
      }
      org.serdaroquai.pml.NodeProto.ValueNode other = (org.serdaroquai.pml.NodeProto.ValueNode) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.serdaroquai.pml.NodeProto.ValueNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.serdaroquai.pml.NodeProto.ValueNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.serdaroquai.pml.ValueNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.serdaroquai.pml.ValueNode)
        org.serdaroquai.pml.NodeProto.ValueNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ValueNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ValueNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.serdaroquai.pml.NodeProto.ValueNode.class, org.serdaroquai.pml.NodeProto.ValueNode.Builder.class);
      }

      // Construct using org.serdaroquai.pml.NodeProto.ValueNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.serdaroquai.pml.NodeProto.internal_static_org_serdaroquai_pml_ValueNode_descriptor;
      }

      @java.lang.Override
      public org.serdaroquai.pml.NodeProto.ValueNode getDefaultInstanceForType() {
        return org.serdaroquai.pml.NodeProto.ValueNode.getDefaultInstance();
      }

      @java.lang.Override
      public org.serdaroquai.pml.NodeProto.ValueNode build() {
        org.serdaroquai.pml.NodeProto.ValueNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.serdaroquai.pml.NodeProto.ValueNode buildPartial() {
        org.serdaroquai.pml.NodeProto.ValueNode result = new org.serdaroquai.pml.NodeProto.ValueNode(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.serdaroquai.pml.NodeProto.ValueNode) {
          return mergeFrom((org.serdaroquai.pml.NodeProto.ValueNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.serdaroquai.pml.NodeProto.ValueNode other) {
        if (other == org.serdaroquai.pml.NodeProto.ValueNode.getDefaultInstance()) return this;
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.serdaroquai.pml.NodeProto.ValueNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.serdaroquai.pml.NodeProto.ValueNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 1;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 1;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.serdaroquai.pml.ValueNode)
    }

    // @@protoc_insertion_point(class_scope:org.serdaroquai.pml.ValueNode)
    private static final org.serdaroquai.pml.NodeProto.ValueNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.serdaroquai.pml.NodeProto.ValueNode();
    }

    public static org.serdaroquai.pml.NodeProto.ValueNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValueNode>
        PARSER = new com.google.protobuf.AbstractParser<ValueNode>() {
      @java.lang.Override
      public ValueNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValueNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValueNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValueNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.serdaroquai.pml.NodeProto.ValueNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_serdaroquai_pml_Node_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_serdaroquai_pml_Node_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_serdaroquai_pml_ExtensionNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_serdaroquai_pml_ExtensionNode_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_serdaroquai_pml_ValueNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_serdaroquai_pml_ValueNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnode.proto\022\023org.serdaroquai.pml\"l\n\004Nod" +
      "e\022/\n\001e\030\001 \001(\0132\".org.serdaroquai.pml.Exten" +
      "sionNodeH\000\022+\n\001v\030\002 \001(\0132\036.org.serdaroquai." +
      "pml.ValueNodeH\000B\006\n\004node\"+\n\rExtensionNode" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014\"\032\n\tValueNod" +
      "e\022\r\n\005value\030\001 \001(\014B\013B\tNodeProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_serdaroquai_pml_Node_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_serdaroquai_pml_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_serdaroquai_pml_Node_descriptor,
        new java.lang.String[] { "E", "V", "Node", });
    internal_static_org_serdaroquai_pml_ExtensionNode_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_serdaroquai_pml_ExtensionNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_serdaroquai_pml_ExtensionNode_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_serdaroquai_pml_ValueNode_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_serdaroquai_pml_ValueNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_serdaroquai_pml_ValueNode_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
